# Generated by Django 4.0.1 on 2022-01-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_alpha', '0002_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
